apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: gitlab-webservice
  namespace: public-service
  labels:
    app: gitlab
    component: webservice
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: gitlab
      component: webservice
