apiVersion: v1
kind: ConfigMap
metadata:
  name: apollo-adminservice
  namespace: public-service
data:
  application-github.properties: |
    spring.datasource.url = jdbc:mysql://192.168.30.131:3306/ApolloConfigDB?characterEncoding=utf8
    spring.datasource.username = root
    spring.datasource.password = 123456789
