apiVersion: v1
kind: Service
metadata:
  name: apollo-adminservice
  namespace: public-service
  labels:
    app: apollo-adminservice
spec:
  selector:
    app: apollo-adminservice
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
