apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  namespace: public-service
  labels:
    app: zk
spec:
  selector:
    app: zk
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
 
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  namespace: public-service
  labels:
    app: zk
spec:
  selector:
    app: zk
  ports:
  - port: 2181
    name: client
