apiVersion: v1
kind: Service
metadata:
  name: gitlab-postgresql
  namespace: public-service
  labels:
    app: gitlab
    component: postgresql
spec:
  type: ClusterIP
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app: gitlab
    component: postgresql
    role: master
