apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    pvname: nfs-mysql-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.30.129
    path: /data/mysql
