apiVersion: v1
kind: ConfigMap
metadata:
  name: apollo-configservice
  namespace: public-service
data:
  application-github.properties: |
    spring.datasource.url = jdbc:mysql://192.168.30.131:3306/ApolloConfigDB?characterEncoding=utf8
    spring.datasource.username = root
    spring.datasource.password = 123456789
    apollo.config-service.url = http://apollo-configservice.public-service:8080
    apollo.admin-service.url = http://apollo-adminservice.public-service:8090
