apiVersion: v1
kind: Service
metadata:
  name: apollo-configservice
  namespace: public-service
  labels:
    app: apollo-configservice
spec:
  selector:
    app: apollo-configservice
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
