apiVersion: v1
kind: ConfigMap
metadata:
  name: apollo-portal
  namespace: public-service
data:
  application-github.properties: |
    spring.datasource.url = jdbc:mysql://192.168.30.131:3306/ApolloPortalDB?characterEncoding=utf8
    spring.datasource.username = root
    spring.datasource.password = 123456789
    apollo.portal.envs = dev
  apollo-env.properties: |
    dev.meta = http://apollo-configservice:8080
