apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-minio
  namespace: public-service
  labels:
    app: gitlab
    component: minio
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
  selector:
    matchLabels:
      app: gitlab
      component: minio
