apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: gitlab-minio-v1
  namespace: public-service
  labels:
    app: gitlab
    component: minio
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: gitlab
      component: minio
