apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner
  namespace: public-service
  labels:
    app: gitlab-runner
type: Opaque
data:
  runner-registration-token: "SHR5WTFBRW9JNUtzUmpKek9aQUExNGVrVUo4YUppQTFDYzA0OWNBWkMwTURGWTVFeU4wa09jdmJUd25DRzdzbA=="             #注册token，base64加密
  runner-token: ""
