apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config-nginx
  namespace: default
  labels:
    app: filebeat
data:
  filebeat.yml: |-
    filebeat.config:
      inputs:
        path: ${path.config}/inputs.d/*.yml
        reload.enabled: false

      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
    filebeat.inputs:
    - type: log
      paths:
        - /logdata/*.log
      tail_files: true
      fields:
        pod_name: '${pod_name}'
        POD_IP: '${POD_IP}'
    setup.template.name: "nginx-logs"
    setup.template.pattern: "nginx-logs-*"

    output.logstash:
      hosts: ["10.96.103.207:5044"]             #指定logstash ClusterIP及端口
      index: "nginx-logs"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config-tomcat
  namespace: default
  labels:
    app: filebeat
data:
  filebeat.yml: |-
    filebeat.config:
      inputs:
        path: ${path.config}/inputs.d/*.yml
        reload.enabled: false

      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
    filebeat.inputs:
    - type: log
      paths:
        - /logdata/*.log
      tail_files: true
      fields:
        pod_name: '${pod_name}'
        POD_IP: '${POD_IP}'
    setup.template.name: "tomcat-logs"
    setup.template.pattern: "tomcat-logs-*"

    output.logstash:
      hosts: ["10.96.103.207:5044"]
      index: "tomcat-logs"
