apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: public-service
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - name: api
    port: 9200
  - name: discovery
    port: 9300
  clusterIP: None
