apiVersion: v1
kind: PersistentVolume
metadata:
  name: alicloud-nas-elfk-pv0
  labels:
    alicloud-pvname: alicloud-nas-elfk-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: alicloud-nas-elfk-pv0
    volumeAttributes:
      server: "xxx.cn-hangzhou.nas.aliyuncs.com"
      path: "/elfk-data/elasticsearch-0"
  mountOptions:
  - nolock,tcp,noresvport
  - vers=4
  
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alicloud-nas-elfk-pv1
  labels:
    alicloud-pvname: alicloud-nas-elfk-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: alicloud-nas-elfk-pv1
    volumeAttributes:
      server: "xxx.cn-hangzhou.nas.aliyuncs.com"
      path: "/elfk-data/elasticsearch-1"
  mountOptions:
  - nolock,tcp,noresvport
  - vers=4
  
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: alicloud-nas-elfk-pv2
  labels:
    alicloud-pvname: alicloud-nas-elfk-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: alicloud-nas-elfk-pv2
    volumeAttributes:
      server: "xxx.cn-hangzhou.nas.aliyuncs.com"
      path: "/elfk-data/elasticsearch-2"
  mountOptions:
  - nolock,tcp,noresvport
  - vers=4
