apiVersion: batch/v1
kind: Job
metadata:
  name: gitlab-shared-secrets-1-7d3
  namespace: public-service
  labels:
    app: gitlab
    component: shared-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      labels:
        app: gitlab
        component: shared-secrets
    spec:
      containers:
        - name: shared-secrets
          image: registry.gitlab.com/gitlab-org/build/cng/kubectl:1.13.12
          imagePullPolicy: IfNotPresent
          command: ['/bin/bash', '/scripts/generate-secrets']
          resources:
            requests:
              cpu: 50m
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: ssh
              mountPath: /etc/ssh
      securityContext:
        runAsUser: 65534
        fsGroup: 65534
      serviceAccountName: gitlab-shared-secrets
      restartPolicy: Never
      volumes:
      - name: scripts
        configMap:
          name: gitlab-shared-secrets
      - name: ssh
        emptyDir: {}
